name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  unit-test:
    name: Unit Test on Java ${{ matrix.java-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version: [17]

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}
          cache: gradle

      - name: Test
        id: unit-test
        run: ./gradlew test

      - name: Upload unit test report
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: maestro-unit-test-report
          path: ./**/build/reports/tests/test
          retention-days: 1
          include-hidden-files: true

  ios-driver-lib-test:
    name: MaestroDriverLib Unit Tests
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Run MaestroDriverLib Tests
        working-directory: ${{ github.workspace }}/maestro-ios-xctest-runner/MaestroDriverLib
        run: swift test

  ios-xctest-runner-test:
    name: iOS XCTest Runner Unit Tests
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Run iOS Unit Tests
        working-directory: ${{ github.workspace }}/maestro-ios-xctest-runner
        run: |
          xcodebuild test \
            -project maestro-driver-ios.xcodeproj \
            -scheme maestro-driver-iosTests \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -only-testing:maestro-driver-iosTests \
            | xcpretty --color || exit ${PIPESTATUS[0]}

  validate-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
